# https://taskfile.dev

version: "3"

tasks:
  init:
    desc: Initialize the project
    deps: [init/frontend, init/backend, init/certs, init/db]

  init/frontend:
    desc: Initialize the front-end project
    //#if(UseReactVite)
    dir: react-vite
    //#endif
    //#if(UseNext)
    dir: react-next
    //#endif
    cmds:
      - yarn install

  init/backend:
    desc: Initialize the back-end project
    dir: AspnextTemplate
    cmds:
      - dotnet restore
      - docker compose build

  init/db:
    desc: Initialize the database
    dir: AspnextTemplate/DB
    cmds:
      - docker compose build

  init/certs:
    desc: Generate self-signed certificates
    cmds:
      - dotnet dev-certs https -ep ${HOME}/.aspnet/https/AspnextTemplate.pfx -p PASSWORD
      - dotnet dev-certs https --trust
      # - openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=localhost"

  run/backend:
    desc: Run the backend
    dir: AspnextTemplate
    cmds:
      //#if(UsePostgreSql)
      - task: run/db
      //#endif
      - docker compose up --build

  //#if(UsePostgreSql)
  run/db: 
    desc: Rund the database
    dir: AspnextTemplate/DB
    cmds:
      - docker compose up --no-recreate -d
  //#endif

  run/frontend:
    desc: Run the frontend
    //#if(UseReactVite)
    dir: react-vite
    //#endif
    //#if(UseNext)
    dir: react-next
    //#endif
    cmds:
      - yarn dev

  run:
    desc: Run the project
    cmds:
      - task: run/backend
      - task: run/frontend
